NOUN = input("Give me a noun, please. ")
NUMBER = input("Now give me a number. ")
VERB = input("A verb, please. ")
NAME = input("Now a name. ")
ADJ = input("An adjective now. ")
VERB2 = input("How about another verb? ")
NOUN2 = input("Gimme a noun! ")
NOUNS = input("A plural noun? ")
NOUNS2 = input("Another one, please! ")
ADVERB = input("An adverb, please (ending in -ly)? ")
NOUN3 = input("Now a noun. ")
NOUN4 = input("...and one last noun, please. ")
NOUNS3 = input("Sorry, I lied. This time is the last one, and please make it plural. ")
VERB3 = input("A verb? ")
ADJ2 = input("One final thing: an adjective :) ") 
print("Here's your story:\nThe "+NOUN+" made its first appearance "+NUMBER+" years ago. It was "+VERB+"ed by Dr. "+NAME+", who originally wanted to make the "+ADJ+" back-"+VERB2+"er. The "+NOUN+" did not immediately catch the public "+NOUN2+" like Dr. "+NAME+" thought. Some "+NOUNS+" later, two "+NOUNS2+" discovered the "+NOUN+", and they "+ADVERB+" saw its use as a "+NOUN3+"! Nowadays, everyone uses their "+NOUN+" daily, and no one would leave their "+NOUN4+" without it! Many "+NOUNS3+" have been "+VERB3+"ed forever thanks to the "+ADJ2+" "+NOUN+"!")
